### PR TITLE
Add 'lint-go' and 'go mod tidy' to GitHub actions

### PR DESCRIPTION
**Pull request by kvendingoldo**

### CODE REVIEW

**Comment by kvendingoldo** [comment]
Should I fix tidy issues in the same PR?

**Comment by kvendingoldo** [comment]
@jgwest @wtam2018  please, review it

**Comment by wtam2018** [comment]
/LGTM

Thanks for the patch.

**Review by jgwest — APPROVED** [review]
LGTM from @wtam2018

**Pull request merged**
