### PR TITLE
Implement E2E test framework for testing ApplicationSet against live Kubernetes/Argo CD instance (#65)

### PR DESCRIPTION
**Pull request by jgwest**
See parent issue for details: https://github.com/argoproj-labs/applicationset/issues/65

To run locally:
- In the PR I've included docs on how to run them (outside the GitHub action), see here: https://github.com/jgwest/applicationset/blob/test-e2e/docs/E2E-Tests.md

### CODE REVIEW

**Comment by amitkrout** [comment]
@jgwest Can you please share the steps for how to verify it, thanks.

**Comment by jgwest** [comment]
@amitkrout Good thinking, I have documented how to do that as a new markdown file in the PR, you can see it here: https://github.com/jgwest/applicationset/blob/test-e2e/docs/E2E-Tests.md

**Review by wtam2018 — COMMENTED** [review]
There is significant amount of copied codes from argocd test/e2e.  Is there a way to shared these codes?

**Comment by jgwest** [comment]
@wtam2018 Only <200 lines of code is shared (part of `fixture.go`, `errors.go`, `cmd.go`), I don't think its worthwhile to share them at this time.

**Review by xianlubird — APPROVED** [review]

**Pull request merged**
