### PR TITLE
Add .golangci.yml from Argo CD, and fix corresponding linter failures

### PR DESCRIPTION
**Pull request by jgwest**
I've added the `.golangci.yml` from Argo CD, with the same enabled linters that it uses, and then fixed all the failing lines.

### CODE REVIEW

**Comment by OmerKahani** [comment]
+1

**Comment by jgwest** [comment]
Hi @xianlubird @dgoodwin @OmerKahani, this PR is ready to be reviewed/merged, feel free to let me know if anything else is required.

**Review by OmerKahani — APPROVED** [review]

**Comment by jgwest** [comment]
Rebased and ready to go.

**Review by wtam2018 — COMMENTED** [review]
LGTM

**Review by xianlubird — APPROVED** [review]

**Pull request merged**
