### PR TITLE
Add git file yaml support

### PR DESCRIPTION
**Pull request by teejaded**
Fixes https://github.com/argoproj-labs/applicationset/issues/106

### CODE REVIEW

**Comment by OmerKahani** [comment]
@teejaded please sign the CLA

**Comment by Gowiem** [comment]
Really looking forward to this one landing -- Thanks for implementing it @teejaded!

**Comment by teejaded** [comment]
Sorry for the delay -- had to do some research to figure out if the CLA was approved by my company.

I added some YAML tests also.

**Comment by mksha** [comment]
Hi Guys,  thanks for adding that functionality , is there any timeline to release this feature ? @teejaded @OmerKahani @jgwest

**Review by jgwest — CHANGES_REQUESTED** [review]
Thanks @teejaded , looks great!

Can you update the Git file generator section of [Generators.md](https://github.com/argoproj-labs/applicationset/blob/master/docs/Generators.md#git-generator-files):
- Update references from JSON to JSON/YAML, where appropriate
- Remove the reference to `!!! note "Supported file formats" Only JSON file parsing is currently supported. The work to add support for YAML files is tracked here.`

Then good to go.

**Comment by mksha** [comment]
@@teejaded can you pls update the doc, Let me know if I can help in any possible way.
thanks

**Comment by mksha** [comment]
@jgwest can you take a look at pr now and approve the pr, pls?

**Pull request merged**
