### PR TITLE
Drop cluster-wide RBAC install and fix finalizer permissions issue.

### PR DESCRIPTION
**Pull request by dgoodwin**
We picked up an ArgoCD pattern where you can install with namespaced or
cluster-wide permissions. The cluster-wide was required so Argo could
potentially sync resources to the cluster it's running in. This however
is not relevant to the ApplicationSet CR, so we do not need to support
dual modes of install and can instead just deploy with namespaced RBAC.

Fix a missing permission for finalizers so we can set an Application
blockOwnerDeletion reference back to the ApplicationSet that is
originated from.

### CODE REVIEW

**Comment by dgoodwin** [comment]
/cc @mgoodness  

As we discussed dropping this cluster scoped install.

**Comment by dgoodwin** [comment]
Fixes this error which surfaces at least with cluster generator:

```
time="2020-09-25T14:37:30Z" level=info msg="matched cluster secret" cluster=cluster-api.dgood-dev.new-installer.openshift.com-3927666468
time="2020-09-25T14:37:30Z" level=info msg="generated 1 applications" generator="&{0xc0003c5980}"
time="2020-09-25T14:37:30Z" level=error msg="failed to unchanged Application" action=unchanged app=admin-configmaps appSet=clustergen error="applications.argoproj.io \"admin-configmaps\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>"
2020-09-25T14:37:30.114Z        ERROR   controller-runtime.controller   Reconciler error        {"controller": "applicationset", "name": "clustergen", "namespace": "argocd", "error": "applications.argoproj.io \"admin-configmaps\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>"}
```

**Comment by OmerKahani** [comment]
@dgoodwin does it fix #52 ?

**Comment by jbaskeen** [comment]
@dgoodwin @OmerKahani the fix here to add `applicationsets/finalizers`  in`base/rbac` resolved my final issue #52

**Comment by dgoodwin** [comment]
Fixes #52

**Review by xianlubird — APPROVED** [review]

**Pull request merged**
