### PR TITLE
added shortnames to the manifests

### PR DESCRIPTION
**Pull request by christianh814**
Something to give us less typing. Added `appsets` and `appset` as `shortNames`

Fixes https://github.com/argoproj-labs/applicationset/issues/196

### CODE REVIEW

**Comment by sbose78** [comment]
+kubebuilder:resource:path=applicationsets,shortName=appset,appsets

@jgwest wonder if we should be doing this in types.go ?

**Comment by sbose78** [comment]
https://github.com/argoproj-labs/applicationset/blob/master/api/v1alpha1/applicationset_types.go#L25

**Comment by jgwest** [comment]
Inadvertently pushed a rebased branch without the new commits, which autoclosed this and can't reopen :smile:. Will open another PR.

**Comment by jgwest** [comment]
@sbose78  @christianh814: new PR with `+kubebuilder` annotations:  https://github.com/argoproj-labs/applicationset/pull/197

**Pull request closed without merging**
